# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('year_pass', models.IntegerField(null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phno', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('no_attending', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='alumnievent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('event', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='c_us_messge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('password1', models.CharField(max_length=50, null=True)),
                ('password2', models.CharField(max_length=50, null=True)),
                ('event', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ec_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='homecoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('no_attending', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=510, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='off_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('ph_no', models.CharField(max_length=200, null=True)),
                ('e_mail', models.CharField(max_length=200, null=True)),
                ('yearin', models.IntegerField(null=True)),
                ('yearout', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='view_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
