# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='a_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='a_country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='a_pin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='a_state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='a_street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='inst_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='lname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='phno',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='student',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='year_pass',
            field=models.IntegerField(null=True),
        ),
    ]
