# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0002_teachers_no_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='attending',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
