# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0003_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='ts',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
