# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0003_teachers_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='attending',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
