# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0005_auto_20171013_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='ts',
        ),
    ]
