# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0005_auto_20171214_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
