# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 16:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0006_remove_notif_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 10, 13, 21, 44, 56, 744277)),
        ),
    ]
