# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0006_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='attend',
            field=models.IntegerField(default=0),
        ),
    ]
