# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0007_auto_20171013_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notif',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
