# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-23 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0007_alumni_attend'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets_offline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('no_attending', models.IntegerField(null=True)),
            ],
        ),
    ]
