# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0008_auto_20171021_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
