# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0009_alumni_registration_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='registration_fee',
        ),
    ]
