# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0010_det'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ec',
            old_name='fname',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='ec',
            old_name='lname',
            new_name='event',
        ),
        migrations.AddField(
            model_name='ec',
            name='password1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ec',
            name='password2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
