# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0010_remove_alumni_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='registration_fee',
            field=models.IntegerField(default=0),
        ),
    ]
