# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0011_auto_20171022_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ec_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='det',
        ),
        migrations.AddField(
            model_name='alumni',
            name='event',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
