# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0013_alumnievent'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnievent',
            name='event',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
