# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0014_alumnievent_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnievent',
            name='event',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
