# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0015_auto_20171101_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnievent',
            name='event',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
