# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0016_auto_20171101_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='homecomeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('no_attending', models.IntegerField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='view_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='alumni',
            name='no_attending',
            field=models.IntegerField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='notif',
            name='fname',
            field=models.CharField(max_length=510, null=True),
        ),
    ]
