# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0017_auto_20171102_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='no_attending',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homecomeing',
            name='no_attending',
            field=models.IntegerField(null=True),
        ),
    ]
