# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0018_auto_20171102_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='homecomeing',
            new_name='homecoming',
        ),
    ]
