# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0019_auto_20171102_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='a_city',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='a_country',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='a_pin',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='a_state',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='a_street',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='event',
        ),
    ]
