# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0020_auto_20171111_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
