# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0021_auto_20171114_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='inst_name',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='student',
        ),
    ]
