# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0022_auto_20171127_1925'),
        ('osat', '0022_auto_20171128_0053'),
    ]

    operations = [
    ]
