# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0023_auto_20171128_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
