# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0024_auto_20171128_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('yearin', models.IntegerField(max_length=200, null=True)),
                ('yearout', models.IntegerField(max_length=200, null=True)),
            ],
        ),
    ]
