# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0025_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='yearin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='yearout',
            field=models.IntegerField(blank=True),
        ),
    ]
