# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0027_auto_20171128_1615'),
        ('osat', '0023_merge_20171128_0824'),
    ]

    operations = [
    ]
