# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0027_auto_20171128_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_us_messge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
