# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0028_merge_20171128_1055'),
        ('osat', '0028_auto_20171203_1136'),
    ]

    operations = [
    ]
