# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osat', '0028_auto_20171203_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='e_mail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='ph_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
